version: "0.0.1"
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresMsInventoryCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_PASSWD}
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local